import io
import random
import numpy as np
import scanpy as sc
from anndata import AnnData
import pandas as pd
import palantir as pt
import cellrank as cr
import scipy.sparse as sp
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from typing import Sequence,Optional, Tuple, Union, Any

random.seed(42)
np.random.seed(42)
n_components_palantir = 15



def palantir_difussion_maps(adata: AnnData, 
    n_components: int = n_components_palantir
) -> AnnData:
    """
    Execute core Palantir preprocessing: Diffusion Maps, Multiscale Space, 
    and MAGIC Imputation.
    Modifies the input `AnnData` object in-place by adding diffusion components
    and imputed gene expression layers.
    Parameters
    ----------
    adata : AnnData
        Annotated single-cell data object.
    n_components : int, optional
        Number of diffusion map components to compute, by default 15.
    Returns
    -------
    AnnData
        The updated AnnData object with computed Palantir components and MAGIC data.
    """

    pt.utils.run_diffusion_maps(adata, n_components=n_components)
    pt.utils.determine_multiscale_space(adata)
    pt.utils.run_magic_imputation(adata)

    return adata


def get_root_cell_palantir(adata: AnnData, cell_subset: Sequence[Union[str, int]]):
    """
    Identify the root cell for Palantir trajectory analysis.
    
    Computes the centroid of a specified cell subset in the multiscaled 
    Diffusion Map space (generated by Palantir) and returns the barcode 
    or index of the cell closest to that centroid.
    Parameters
    ----------
    adata : AnnData
        Annotated data object containing Palantir eigenvectors in 
        `.obsm['DM_EigenVectors_multiscaled']`.
    cell_subset : Sequence[Union[str, int]]
        A sequence of cell barcodes or indices representing the candidate subset of cells
        (e.g., cells belonging to a stem or progenitor cluster).
    Returns
    -------
    Union[str, int]
        The cell identifier or index from `cell_subset` closest to the centroid.
    """

    dm_coords = adata[cell_subset].obsm['DM_EigenVectors_multiscaled']
    centroid = dm_coords.mean(axis=0)
    dists = np.linalg.norm(dm_coords - centroid, axis=1)
    return cell_subset[np.argmin(dists)]


def get_lgr5_expression(adata: AnnData, 
    gene_name: str = "Lgr5",
    layer: Optional[str] = None, 
    ) -> np.ndarray:
    """
    Extract expression values for a target gene (default: Lgr5) across all cells.
    Handles both sparse matrices (e.g. scipy CSR/CSC) and dense NumPy arrays 
    stored either in `adata.X` or in a specified layer (e.g., MAGIC imputed data).
    Parameters
    ----------
    adata : AnnData
        Annotated single-cell data object.
    gene_name : str, default="Lgr5"
        The gene symbol to locate within `adata.var_names`.
    layer : Optional[str], default=None
        Name of the layer in `adata.layers` to pull data from (e.g., 'MAGIC_imputed').
        If None, data is pulled directly from `adata.X`.
   
    Returns
    -------
    np.ndarray
        1D NumPy array containing the gene expression values for all cells.
    """
    idx = adata.var_names.get_loc(gene_name)
    X = adata.layers[layer] if layer else adata.X
    expr = X[:, idx]
    if sp.issparse(expr):
        expr = expr.toarray().flatten()
    else:
        expr = np.asarray(expr).flatten()
    return expr


def centroid_root_cells_lgr5( adata: AnnData, 
    name_score_fetal: str, 
    layer: Optional[str] = None,
    n_top_cells: int = 20
) -> Tuple[Union[str, int], Union[str, int]]:
    """
    Determine biological root cells for Fetal-like and WNT (Lgr5+) lineages.
    Identifies the top N cells with the highest fetal signature score and the top N 
    cells with the highest Lgr5 expression, then computes their respective 
    centroid-based root cells in the Palantir multiscaled diffusion space.
    Parameters
    ----------
    adata : AnnData
        Annotated single-cell data object containing Palantir multiscaled space.
    name_score_fetal : str
        Column key in `adata.obs` representing the fetal signature score.
    layer : Optional[str], default=None
        Layer name in `adata.layers` to extract Lgr5 expression from (e.g., 'MAGIC_imputed').
    n_top_cells : int, default=20
        Number of top-scoring cells to use for centroid calculation.
    Returns
    -------
    Tuple[Union[str, int], Union[str, int]]
        A tuple `(root_A, root_B)` containing:
        - `root_A`: Barcode/index of the biological Fetal-like root cell.
        - `root_B`: Barcode/index of the biological WNT (Lgr5+) root cell.
    """

    top_fetal_cells = adata.obs.nlargest(n_top_cells, name_score_fetal).index
    # Compute the centroid-based root cell for the Fetal-like lineage
    root_A = get_root_cell_palantir(adata, top_fetal_cells)

    # Compute the centroid-based root cell for the WNT (Lgr5+) lineage
    lgr5_expr = get_lgr5_expression(adata, layer=layer)

    # Temporarily store Lgr5 expression in adata.obs for easy ranking via pandas nlargest
    adata.obs["_lgr5_tmp"] = lgr5_expr
    top_lgr5_cells = adata.obs.nlargest(n_top_cells, "_lgr5_tmp").index

    # Compute the centroid-based root cell for the WNT (Lgr5+) lineage
    root_B = get_root_cell_palantir(adata, top_lgr5_cells)

    #Clean up temporary column from adata.obs to maintain a clean metadata matrix
    adata.obs.drop(columns="_lgr5_tmp", inplace=True)

    print(f"Root Fetal-like biologica: {root_A}")
    print(f"Root WNT biologica (Lgr5+): {root_B}")
    return root_A, root_B


def plot_root_cells(adata: AnnData, 
    root_A: Union[str, int], 
    root_B: Union[str, int],
    show: bool = True
    ) -> None:
    """
    Visualize identified biological root cells on a UMAP plot.
    Highlights the Fetal-like root cell (root_A) and WNT root cell (root_B) 
    in distinct colors against the background of all other cells in UMAP space.
    Parameters
    ----------
    adata : AnnData
        Annotated single-cell data object containing UMAP coordinates (`.obsm['X_umap']`).
    root_A : Union[str, int]
        Barcode or index of the Fetal-like lineage root cell.
    root_B : Union[str, int]
        Barcode or index of the WNT (Lgr5+) lineage root cell.
    show : bool, default=True
        Whether to display the figure inline.
    """

    adata.obs["Root_Highlight"] = "Other Cells"
    adata.obs.loc[root_A, "Root_Highlight"] = "Root_Fetal_A"
    adata.obs.loc[root_B, "Root_Highlight"] = "Root_WNT_B"

    color_dict = {
        "Other Cells": "#E0E0E0",
        "Root_Fetal_A": "#FF0000",
        "Root_WNT_B": "#0000FF",
    }

    plt.figure(figsize=(8, 8))
    sc.pl.umap(
        adata,
        color="Root_Highlight",
        palette=color_dict,
        groups=[
            "Root_Fetal_A",
            "Root_WNT_B",
        ],
        size=100,
        show=show
    )


def run_palantir(adata: AnnData, 
    root_cell: Union[str, int], 
    terminal_cell: Union[str, int, Sequence[Union[str, int]]],
    expression_key: str = "MAGIC_imputed_data"
    ) -> Tuple[Any, Any]:
    """
    Run Palantir pseudotime, branch selection, trajectory plotting, and gene trends.
    Calculates pseudotime and branch probabilities starting from a designated 
    root cell towards terminal state(s), determines branch membership masks, 
    plots trajectories, and computes gene expression trends along pseudotime.
    Parameters
    ----------
    adata : AnnData
        Annotated single-cell data object pre-processed with Palantir diffusion maps.
    root_cell : Union[str, int]
        Barcode or index of the designated starting (root) cell.
    terminal_cell : Union[str, int, Sequence[Union[str, int]]]
        Single barcode/index or sequence of barcodes representing terminal state(s).
    expression_key : str, default="MAGIC_imputed_data"
        Key in `adata.layers` or `adata.obsm` containing the imputed expression matrix 
        used for computing gene trends.
    Returns
    -------
    Tuple[Any, Any]
        A tuple `(palantir_results, masks)` containing:
        - `palantir_results`: Palantir output object containing pseudotime and branch probabilities.
        - `masks`: Pandas DataFrame containing binary cell membership masks for each trajectory branch.
    """
    palantir_results = pt.core.run_palantir(
        adata,
        root_cell,
        terminal_states=[terminal_cell],
        num_waypoints=len(adata),
        use_early_cell_as_start=False,
    )
    masks = pt.presults.select_branch_cells(adata)
    pt.plot.plot_trajectories(adata, pseudotime_interval=(0, 1.0), figsize=(8, 5))

    pt.presults.compute_gene_trends(adata, expression_key=expression_key)

    return palantir_results, masks


def rename_trajectory(adata: AnnData, old_name: str, new_name: str
    ) -> AnnData:
    """
    Rename a trajectory branch across Palantir metadata structures in AnnData.
    Updates column names in `branch_masks`, `palantir_fate_probabilities`, 
    and updates key-value pairs in the color mapping dictionary (`palantir_fates_colors`).
    Parameters
    ----------
    adata : AnnData
        Annotated single-cell data object containing Palantir results.
    old_name : str
        Existing name of the trajectory branch (e.g., raw terminal cell ID).
    new_name : str
        New descriptive label for the trajectory branch (e.g., 'Enterocyte_Lineage').
    Returns
    -------
    AnnData
        The modified AnnData object with renamed trajectory metadata.
    """

    # Rename column in the branch membership masks DataFrame
    if "branch_masks" in adata.obsm:
        adata.obsm["branch_masks"] = adata.obsm["branch_masks"].rename(
            columns={old_name: new_name}
        )
    # Rename column in the fate probabilities DataFrame
    if "palantir_fate_probabilities" in adata.obsm:
        adata.obsm["palantir_fate_probabilities"] = adata.obsm[
            "palantir_fate_probabilities"
        ].rename(columns={old_name: new_name})

    # Update the trajectory branch color mapping dictionary in adata.uns
    if "palantir_fates_colors" in adata.uns:
        colore = adata.uns["palantir_fates_colors"].pop(old_name, "#2b5c8f")
        adata.uns["palantir_fates_colors"][new_name] = colore

    return adata

def run_cellrank(adata: AnnData, 
    time_key: str = "palantir_pseudotime",
    threshold_scheme: str = "soft"
    ) -> cr.kernels.PseudotimeKernel:
    """
    Initialize and compute a CellRank PseudotimeKernel using Palantir pseudotime.
    Constructs a directed cell-to-cell transition matrix derived from pseudotime 
    ordering, enabling downstream CellRank trajectory estimators (e.g., GPCCA).
    Parameters
    ----------
    adata : AnnData
        Annotated single-cell data object containing computed pseudotime in `adata.obs`.
    time_key : str, default="palantir_pseudotime"
        Column key in `adata.obs` containing the pseudotime values.
    threshold_scheme : str, default="soft"
        Scheme used for computing transition probabilities ('soft', 'hard', or 'lump').
    Returns
    -------
    cr.kernels.PseudotimeKernel
        The computed CellRank PseudotimeKernel instance ready for downstream estimators.
    """

    # Initialize CellRank PseudotimeKernel using Palantir pseudotime values
    pk = cr.kernels.PseudotimeKernel(adata, time_key=time_key)
    pk.compute_transition_matrix(threshold_scheme=threshold_scheme)
    return pk


def unique_figure(
    adata: AnnData,
    pk: cr.kernels.PseudotimeKernel,
    PSEUDOTIME_KEY: str = "palantir_pseudotime",
    PANEL_CMAP: str = "Spectral_r",
    GENE_PANEL: Sequence[str] = ("Cxcr4", "Lgr5", "Axin2", "Nkd1", "Anxa3", "Anxa1", "Tacstd2"),
    output_pdf: str = "Palantir_3Donors_Grid.pdf"
) -> None:
    """
    Compile a multi-panel summary figure combining Palantir trajectories and CellRank projections.
    Renders a stacked 4-row figure consisting of:
    1. Palantir trajectory UMAP embedding
    2. Gene-trend heatmaps along pseudotime
    3. Branch-specific smoothed expression curves (Tacstd2, Lgr5, Cxcr4)
    4. CellRank directed pseudotime vector field projection
    Parameters
    ----------
    adata : AnnData
        Annotated single-cell data object containing Palantir results and gene trends.
    pk : cr.kernels.PseudotimeKernel
        Computed CellRank PseudotimeKernel instance containing transition probabilities.
    PSEUDOTIME_KEY : str, default="palantir_pseudotime"
        Metadata key in `adata.obs` containing pseudotime values.
    PANEL_CMAP : str, default="Spectral_r"
        Matplotlib color map used for rendering pseudotime trajectories.
    GENE_PANEL : Sequence[str], default=("Cxcr4", "Lgr5", ...)
        List or tuple of gene symbols to visualize in the trend heatmap.
    output_pdf : str, default="Palantir_3Donors_Grid.pdf"
        File path destination for the exported multi-panel PDF figure.
    """

    def plot_gene_expression_premium(
        df_expr,
        branch_name,
        color_trop2="#c02ded",  # Pink
        color_lgr5="#2D5A43",   # Wnt Gold
        color_cxcr4="#08A047",  # Crimson
        linewidth=1,
        scale_min_max=True,
        title=None,
        figsize=(3, 3),
    ):
        """Same premium branch-expression plot as the original notebook, returning the Figure
        instead of calling plt.show() so it can be embedded as a grid panel."""
        # 1. Slice DataFrame by Branch
        df_branch = None
        if branch_name in df_expr.columns.levels[0]:
            df_branch = df_expr[branch_name]
        else:
            # Fallback if MultiIndex isn't present
            df_branch = df_expr

        # 2. Extract Pseudotime Index & Gene Expression Trends
        pseudotime = df_branch.index.values.astype(float)

        # Case-insensitive helper to grab gene series safely
        def get_gene(df, name):
            match = [c for c in df.columns if str(c).lower() == name.lower()]
            if match:
                return df[match[0]].values.flatten()
            raise KeyError(
                f"Gene '{name}' not found in DataFrame. Available genes: {list(df.columns)}"
            )

        tacstd2_expr = get_gene(df_branch, "Tacstd2")
        lgr5_expr = get_gene(df_branch, "Lgr5")
        cxcr4_expr = get_gene(df_branch, "Cxcr4")

        # 3. Min-Max Normalization (Gene-wise)
        if scale_min_max:
            def min_max_scale(x):
                xmin, xmax = np.nanmin(x), np.nanmax(x)
                return (x - xmin) / (xmax - xmin) if xmax > xmin else np.zeros_like(x)

            tacstd2_expr = min_max_scale(tacstd2_expr)
            lgr5_expr = min_max_scale(lgr5_expr)
            cxcr4_expr = min_max_scale(cxcr4_expr)

        # 4. Styling & Plotting
        plt.rcParams["font.family"] = "sans-serif"
        plt.rcParams["font.sans-serif"] = ["Arial", "Helvetica", "DejaVu Sans"]

        fig, ax = plt.subplots(figsize=figsize, dpi=200)

        # Plot Curves
        ax.plot(
            pseudotime,
            tacstd2_expr,
            label="Tacstd2",
            color=color_trop2,
            linewidth=linewidth,
            zorder=3,
        )
        ax.fill_between(
            pseudotime, tacstd2_expr, color=color_trop2, alpha=0.01, zorder=2
        )

        ax.plot(
            pseudotime,
            lgr5_expr,
            label="Lgr5",
            color=color_lgr5,
            linewidth=linewidth,
            zorder=3,
        )
        ax.fill_between(pseudotime, lgr5_expr, color=color_lgr5, alpha=0.01, zorder=2)

        ax.plot(
            pseudotime,
            cxcr4_expr,
            label="Cxcr4",
            color=color_cxcr4,
            linewidth=linewidth,
            zorder=3,
        )
        ax.fill_between(pseudotime, cxcr4_expr, color=color_cxcr4, alpha=0.01, zorder=2)

        # Spines & Grid
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_color("#cccccc")
        ax.spines["bottom"].set_color("#cccccc")

        ax.grid(axis="y", linestyle="--", alpha=0.4, color="#cccccc", zorder=1)
        ax.grid(False, axis="x")
        # Labels & Limits
        if title:
            ax.set_title(title, fontsize=12, pad=15, color="#222222")

        ax.set_xlabel("Trajectory Pseudotime", fontsize=10, labelpad=6, color="#333333")
        ax.set_ylabel(
            "Relative Expression" if scale_min_max else "Expression",
            fontsize=10,
            labelpad=6,
            color="#333333",
        )

        ax.tick_params(colors="#555555", labelsize=9)
        ax.set_xlim(0, 1)
        ax.set_ylim(-0.02, 1.05)

        # Legend
        ax.legend(
            loc="upper center",
            bbox_to_anchor=(0.5, 1.18),
            ncol=3,
            frameon=False,
            fontsize=9,
            handletextpad=0.5,
            columnspacing=1.5,
        )

        fig.tight_layout()
        return fig

    def fig_to_array(fig, dpi=200):
        """Rasterize a matplotlib Figure to an RGBA array and close it."""
        buf = io.BytesIO()
        fig.savefig(buf, format="png", dpi=dpi, bbox_inches="tight", facecolor="white")
        plt.close(fig)
        buf.seek(0)
        return plt.imread(buf)

    def render_trajectory_panel(figsize=(5.4, 5.0)):
        fig = plt.figure(figsize=figsize)
        ax = fig.add_subplot(111)
        pt.plot.plot_trajectories(
            adata,
            pseudotime_interval=(0, 1.0),
            lw=0.5,
            scanpy_kwargs={"size": 25, "cmap": PANEL_CMAP},
            ax=ax,
        )
        if len(fig.axes) > 1:
            cax = fig.axes[-1]  # colorbar axis is always created last
            pos = cax.get_position()
            shrink_factor = 0.5
            new_height = pos.height * shrink_factor
            new_y0 = pos.y0 + (pos.height - new_height) / 2
            cax.set_position([pos.x0, new_y0, pos.width, new_height])

        return fig

    def render_heatmap_panel(width=4.4, row_height=0.4):
        fig = pt.plot.plot_gene_trend_heatmaps(
            adata, GENE_PANEL, cmap="coolwarm", basefigsize=(width, row_height)
        )
        return fig

    def render_expression_panel(figsize=(4.4, 3.4)):
        branches = list(adata.obsm["palantir_fate_probabilities"].columns)
        n_points = adata.varm[f"gene_trends_{branches[0]}"].shape[1]
        pseudotime_grid = np.linspace(0, 1, n_points)

        df_expr = pd.concat(
            {br: adata.varm[f"gene_trends_{br}"].loc[GENE_PANEL].T for br in branches},
            axis=1,
        )
        df_expr.index = pseudotime_grid
        df_expr.index.name = "pseudotime"

        return plot_gene_expression_premium(
            df_expr,
            branch_name=branches[0],
            scale_min_max=True,
            title=None,
            figsize=figsize,
        )

    def render_cellrank_panel(figsize=(4.4, 4.0)):
        fig, ax = plt.subplots(figsize=figsize)
        pk.plot_projection(
            basis="X_umap",
            color=PSEUDOTIME_KEY,
            color_map=PANEL_CMAP,
            size=25,
            legend_loc=None,
            colorbar=True,
            alpha=1.0,
            ax=ax,
            show=False,
        )
        ax.grid(False)
        return fig

    ROW_BUILDERS = [
        ("Palantir trajectory", render_trajectory_panel),
        ("Gene-trend heatmap", render_heatmap_panel),
        ("Branch expression", render_expression_panel),
        ("CellRank projection", render_cellrank_panel),
    ]

    # Render every panel once up front (also used to size grid rows by real aspect ratio)
    panel_images = {}
    for row_label, builder in ROW_BUILDERS:
        panel_images[(row_label)] = fig_to_array(builder())

    # Row heights follow each panel's own rendered aspect ratio, so no panel is stretched/squeezed
    n_rows = len(ROW_BUILDERS)
    n_cols = 1
    col_width = 4.4
    row_labels = [label for label, _ in ROW_BUILDERS]

    row_aspect = [
            panel_images[(label)].shape[0] / panel_images[(label)].shape[1]
        for label in row_labels
    ]
    row_heights = [a * col_width for a in row_aspect]

    fig_width = n_cols * col_width + 0.9  # extra margin for row labels
    fig_height = sum(row_heights) + 0.6  # extra margin for the page title

    fig = plt.figure(figsize=(fig_width, fig_height))
    gs = gridspec.GridSpec(
        n_rows,
        n_cols,
        figure=fig,
        height_ratios=row_heights,
        left=0.09,
        right=0.99,
        top=0.94,
        bottom=0.02,
        hspace=0.15,
        wspace=0.05,
    )

    for r, label in enumerate(row_labels):
        ax = fig.add_subplot(gs[r])
        ax.imshow(panel_images[(label)])
        ax.set_xticks([])
        ax.set_yticks([])
        for spine in ax.spines.values():
            spine.set_visible(False)
        ax.set_ylabel(label, fontsize=11, rotation=90, labelpad=8)

    fig.savefig(output_pdf, format="pdf", dpi=300)
    plt.show()
